name: Post n8n Feedback to PR

on:
  workflow_dispatch:
    inputs:
      run_token:
        description: 'UUID correlation token from initial workflow'
        required: true
      pr_number:
        description: 'Pull Request Number'
        required: true
      comment:
        description: 'Feedback or comment to post on PR'
        required: true

jobs:
  post-n8n-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Log correlation token for traceability
        run: echo "Correlation token: ${{ github.event.inputs.run_token }}"

      - name: Post feedback comment to PR
        run: |
          gh pr comment ${{ github.event.inputs.pr_number }} --body "${{ github.event.inputs.comment }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}