name: Trigger n8n Webhook with PR Details

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-n8n-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details from GitHub API
        id: pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send PR details to n8n Webhook
        env:
          PR_DATA: ${{ steps.pr.outputs.data }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$PR_DATA" \
            https://YOUR_N8N_URL/webhook/8bdbd1e3-f7bf-4bec-ae9d-9535ef6158a2