name: Trigger n8n Webhook

on:
  push:  # Triggers on every push to any branch

jobs:
  call-n8n-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to n8n Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"message": "Triggered by push to ${GITHUB_REF}"}' \
            https://n8n.papermoon.io/webhook-test/8bdbd1e3-f7bf-4bec-ae9d-9535ef6158a2