name: Trigger n8n Webhook

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to send to n8n Webhook'
        required: false
        default: 'Hello from GitHub Actions!'

jobs:
  call-n8n-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to n8n Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"${{ github.event.inputs.message }}\"}" \
            https://n8n.papermoon.io/webhook-test/8bdbd1e3-f7bf-4bec-ae9d-9535ef6158a2